const STORAGE_KEY="culture-guide-data-v1";
const N={monument:"Памятник",museum:"Музей",architecture:"Архитектура",religion:"Храм",nature:"Природа",culture:"Культура",other:"Другое"};
const COLORS=["#e11d48","#2563eb","#16a34a","#9333ea","#ea580c","#0891b2","#ca8a04"];
let data,currentCity,map,markers=[],active=new Set(Object.keys(N));
const $=id=>document.getElementById(id);
async function load(){const s=localStorage.getItem(STORAGE_KEY);if(s)return JSON.parse(s);return (await fetch("data/cities.json")).json()}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(data))}
function city(){return data.cities.find(x=>x.id===currentCity)}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function km(a,b){const r=Math.PI/180,R=6371,dl=(b.lat-a.lat)*r,do_=(b.lon-a.lon)*r,x=Math.sin(dl/2)**2+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin(do_/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function graph(ps){if(ps.length<2)return[];const used=new Set([0]),es=[];while(used.size<ps.length){let best=null;for(const i of used)for(let j=0;j<ps.length;j++)if(!used.has(j)){const d=km(ps[i],ps[j]);if(!best||d<best.d)best={i,j,d}}es.push(best);used.add(best.j)}const set=new Set(es.map(e=>[Math.min(e.i,e.j),Math.max(e.i,e.j)].join("-")));for(let i=0;i<ps.length;i++){const ns=[...ps.keys()].filter(j=>j!==i).map(j=>({j,d:km(ps[i],ps[j])})).sort((a,b)=>a.d-b.d);if(ns[0]&&ns[0].d<2.5){const k=[Math.min(i,ns[0].j),Math.max(i,ns[0].j)].join("-");if(!set.has(k)){es.push({i,j:ns[0].j,d:ns[0].d});set.add(k)}}}return es}
function lines(ps,es){const a=ps.map(()=>[]);es.forEach((e,i)=>{a[e.i].push({to:e.j,i});a[e.j].push({to:e.i,i})});const used=new Set(),out=[];const starts=a.map((x,i)=>x.length!==2?i:-1).filter(i=>i>=0);for(const s of starts)for(const e of a[s]){if(used.has(e.i))continue;let n=[s],p=s,c=e.to;used.add(e.i);n.push(c);while(a[c].length===2){const z=a[c].find(x=>x.to!==p&&!used.has(x.i));if(!z)break;used.add(z.i);p=c;c=z.to;n.push(c)}out.push(n)}es.forEach((e,i)=>{if(!used.has(i))out.push([e.i,e.j])});return out}
function render(){const c=city();$("mapTitle").textContent=c.name+(c.region?", "+c.region:"");map.setView(c.center,14);markers.forEach(m=>m.remove());markers=[];const q=$("search").value.toLowerCase(),ps=c.places.filter(p=>active.has(p.category)&&p.name.toLowerCase().includes(q));ps.forEach(p=>{const m=L.circleMarker([p.lat,p.lon],{radius:8,weight:2,color:"#fff",fillColor:({"monument":"#e11d48","museum":"#7c3aed","architecture":"#2563eb","religion":"#ca8a04","nature":"#16a34a","culture":"#0891b2","other":"#64748b"})[p.category],fillOpacity:.95});m.bindPopup('<b>'+esc(p.name)+'</b><br><small>'+N[p.category]+'</small><p>'+esc(p.description)+'</p>');m.addTo(map);markers.push(m)});$("stats").innerHTML='<div class="stat"><b>'+c.places.length+'</b><span>объектов</span></div><div class="stat"><b>'+c.places.filter(p=>p.category==="museum").length+'</b><span>музеев</span></div>';$("filters").innerHTML=[...new Set(c.places.map(p=>p.category))].map(x=>'<button class="filter '+(active.has(x)?"active":"")+'" data-c="'+x+'">'+N[x]+'</button>').join("");document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{active.has(b.dataset.c)?active.delete(b.dataset.c):active.add(b.dataset.c);render()});$("places").innerHTML=ps.map(p=>'<div class="place" data-lat="'+p.lat+'" data-lon="'+p.lon+'"><strong>'+esc(p.name)+'</strong><small>'+N[p.category]+'</small></div>').join("");document.querySelectorAll(".place").forEach(x=>x.onclick=()=>map.setView([+x.dataset.lat,+x.dataset.lon],16));draw(c)}
function draw(c){const ps=c.places,es=graph(ps),ls=lines(ps,es),w=Math.max(850,$("scheme").clientWidth||850),h=430,pad=55,minLa=Math.min(...ps.map(p=>p.lat)),maxLa=Math.max(...ps.map(p=>p.lat)),minLo=Math.min(...ps.map(p=>p.lon)),maxLo=Math.max(...ps.map(p=>p.lon)),X=x=>pad+(x-minLo)/((maxLo-minLo)||1)*(w-2*pad),Y=y=>pad+(maxLa-y)/((maxLa-minLa)||1)*(h-2*pad);let s='<svg viewBox="0 0 '+w+' '+h+'">';ls.forEach((l,k)=>{const q=l.map(i=>[X(ps[i].lon),Y(ps[i].lat)]),d=q.map((p,i)=>(i?'L':'M')+p[0].toFixed(1)+' '+p[1].toFixed(1)).join(' ');s+='<path class="line" stroke="'+COLORS[k%COLORS.length]+'" d="'+d+'"/>'});const deg=ps.map(()=>0);es.forEach(e=>{deg[e.i]++;deg[e.j]++});ps.forEach((p,i)=>{const x=X(p.lon),y=Y(p.lat);s+='<circle class="station '+(deg[i]>2?'interchange':'')+'" cx="'+x+'" cy="'+y+'" r="'+(deg[i]>2?9:7)+'"/><text class="station-label" x="'+(x+12)+'" y="'+(y+4)+'">'+esc(p.name)+'</text>'});s+='</svg>';$("scheme").innerHTML='<div class="scheme">'+s+'</div>'}
$("citySelect").onchange=e=>{currentCity=e.target.value;render()};$("search").oninput=render;$("rebuildBtn").onclick=()=>draw(city());
$("exportBtn").onclick=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));a.download="culture-guide-data.json";a.click()};
$("importFile").onchange=async e=>{try{data=JSON.parse(await e.target.files[0].text());currentCity=data.cities[0].id;save();cityList();render()}catch(x){alert(x.message)}};
function cityList(){$("citySelect").innerHTML=data.cities.map(c=>'<option value="'+c.id+'">'+esc(c.name)+', '+esc(c.country)+'</option>').join("");$("citySelect").value=currentCity}
$("addCityBtn").onclick=()=>{const name=$("newCityName").value.trim(),country=$("newCountry").value.trim(),lat=+$("newLat").value,lon=+$("newLon").value;if(!name||!Number.isFinite(lat)||!Number.isFinite(lon))return alert("Нужны название и координаты");const id="city-"+Date.now();data.cities.push({id,name,country,center:[lat,lon],places:[]});currentCity=id;save();cityList();render()};
$("addPlaceBtn").onclick=()=>{const c=city(),name=$("placeName").value.trim(),lat=+$("placeLat").value,lon=+$("placeLon").value;if(!c||!name||!Number.isFinite(lat)||!Number.isFinite(lon))return alert("Нужны название и координаты");c.places.push({id:"place-"+Date.now(),name,category:$("placeCategory").value,description:$("placeDescription").value.trim(),lat,lon});save();render()};
(async()=>{data=await load();currentCity=data.cities[0].id;cityList();map=L.map("map").setView(city().center,14);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"© OpenStreetMap contributors"}).addTo(map);render()})();